### ISSUE TITLE
Inventory interface examine boxes go off screen

### ISSUE THREAD

**Issue by Zoboomaku** [Cyborger1/examine-tooltip#11]
Items examined in the inventory, especially those in the right two columns, [display off-screen.](https://github.com/Cyborger1/examine-tooltip/assets/32339249/ad30b4d2-5409-4f0c-bf03-62e6b1157734)

**Comment by Cyborger1** [comment]
I'm not sure why this would happen, it seems fine on my side.

![image](https://github.com/Cyborger1/examine-tooltip/assets/45152844/8e0d50e3-abd8-4b7d-a36c-6eb293d93268)

The behavior you're describing could only happen if the examine is somehow not recognized as an interface examine and the "Clamp RS3 examine boxes" is not checked, or if Runelite is reporting wrong screen bounds ot the plugin.

Can you tell me what you set on the "Clamp RS3 examine boxes" setting?

**Comment by Cyborger1** [comment]
If you relaunch Runelite, does it do it on the first examine or does the problem happen after examining a few things?

**Comment by Zoboomaku** [comment]
Just restarted and relaunched and it still happened on first examine

**Comment by Cyborger1** [comment]
Do you have a list of hub plugins you have installed? Maybe one of them is conflicting somehow.

**Comment by Cyborger1** [comment]
Actually can you provide me a log from `%userprofile%\.runelite\logs\client.log`? I want to confirm that the plugin isn't throwing any errors.

**Comment by Cyborger1** [comment]
I've been able to replicate the issue, it's related to using Stretched Mode. I will look for a way to fix this.

**Comment by Cyborger1** [comment]
I fixed the problem, I will PR an update on the plugin hub shortly.

**Comment by Cyborger1** [comment]
Once the PR above is merged, please relaunch Runelite and let me know if the issue is fixed.

**Comment by Zoboomaku** [comment]
Just got the update and it's working for me now.

Thanks for your quick work, you're awesome

**Comment by Zoboomaku** [comment]
Just got the update and it's working for me now.

Thanks for your quick work, you're awesome
