### ISSUE TITLE
Feature Request: Make this plugin work when Inspecting farming patches

### ISSUE THREAD

**Issue by ShaunDreclin** [Cyborger1/examine-tooltip#2]

**Comment by Cyborger1** [comment]
This is actually something I had started working on (and got mostly working) about three months ago in a [different branch](https://github.com/Cyborger1/examine-tooltip/tree/patch-inspects) of this project, but I never got around to fully testing it.

I'll start looking at it again, but it would be much appreciated if you could run the plugin from that branch and tell me if you get any issues with it, but it's ok if you don't want to.
