### ISSUE TITLE
Feature Request: Compatibility with the Patch Payment hub plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [Cyborger1/examine-tooltip#4]
https://github.com/PolishToaster/patch-payment

Support for both the examine and check options would be good, but just examine would get the job done too. Cross-posted this to their repo

**Comment by Cyborger1** [comment]
I coded this plugin with the default client behaviour in mind. If I were to start adding exceptions for other plugin hub plugins, I feel this would become unmanageable very quickly.

In this specific case, the plugin in question adds a "Check" option to seeds. The thing about the "Examine" option is that it consistently does the same thing across every item, object or NPC in the game, but "Check" can do different things.

For example, a Gem Bag, when checked, will print a chat message, but a Seed Box opens an interface instead. I would need to have logic to account for every valid ItemIDs where this plugin could work with a "Check" option. Now, that is not out of the question for this plugin to have eventually, but if other plugins start adding "Check" options to items, I can't keep track of that.

The payment plugin also alters the behaviour of the "Examine" function it seems, adding a second message of a type my plugin was not expecting. Again, for my plugin to work, I would need to have specific logic for this situation. I also never coded this to support items producing more than one chat message and stacking them.

I'm sorry, but I feel getting this kind of cross-compatibility to work would not only be a lot of work for a very niche situation, but also open the floodgates to this plugin trying to be compatible with any other plugin that alters the basic "Examine" behaviour.

I am considering this out-of-scope of this project and closing this as a "wont fix". Sorry.

**Comment by ShaunDreclin** [comment]
Fair enough! No worries

**Comment by Cyborger1** [comment]
I have a proposed solution that would work with both the examine and check part of the plugin, but only works with the "tooltip" mode of this plugin. The box would always appear under the cursor the same way Price Checks do.

https://github.com/Cyborger1/examine-tooltip/compare/patch-payment
