### ISSUE TITLE
Interface item examines don't appear

### ISSUE THREAD

**Issue by Aegarain** [Cyborger1/examine-tooltip#8]
As in title. When the "Show interface item examines" box is checked, examining an item in the inventory won't show the examine text in a infobox. It will only appear in the chat window

**Comment by Cyborger1** [comment]
I'll look into it, I think I saw something about the ops for examines in the inventory changing recently. I don't know when I'll have time to push a fix though. Thanks for raising the issue.

**Comment by Cyborger1** [comment]
I did a quick check, looks like inventory examines now work the same way as other interfaces, so taking out the specific logic for that and bringing it back to the other type seems to fix the issue. If you are able to build hub plugins, you may test the PR I linked to this issue.

I don't have time to 100% test this yet but I'll try to PR this to the hub before the end of the week.
